#!/usr/bin/with-contenv bash


# create symlinks
i=/app/bbuddy/data
[[ -e "$i" && ! -L "$i" && -e /data ]] && \
        rm -Rf "$i" && \
        ln -s /data "$i"
[[ -e "$i" && ! -L "$i" ]] && \
	mv "$i" /data && \
	ln -s /data "$i"

chown -R abc:abc \
    /app/bbuddy \
    /config
    /data
